#!/bin/bash
if [[ -z $2 ]];then
    echo '参数错误'
    exit
fi

application_name=$2
package_suffix=$3
pid_path='/data/jar/run/pid/'
pid_file=${pid_path}${application_name}.pid
application_path='/data/jar/'
application=${application_path}${application_name}.${package_suffix}
lock_path='/data/jar/run/lock/'
lockfile=${lock_path}${application_name}
log_path='/data/logs/all-tomcat-logs/'${application_name}''
log_file=${log_path}'/start.log'
start() {
        echo -n $"Starting ${application_name} logger: "
        if [[ ! -d ${pid_path} ]];then
            mkdir -p ${pid_path}
        fi
        if [[ ! -d ${lock_path} ]];then
            mkdir -p ${lock_path}
        fi
        if [[ ! -d ${log_path} ]];then
            mkdir -p ${log_path}
        fi
        if [[ ! -f ${pid_file} ]];then
            date=`date +%Y-%m-%d-%H%M`
            log_files=`find ${log_path} -name \*.log`
            if [[ $? -eq 0 ]];then
                for log in ${log_files}
                do
                    mv ${log} ${log}-${date}
                done
            else
                echo ${log_path} 不存在
            fi
            nohup java -jar -Dspring.cloud.config.profile=test ${application} >> ${log_file} 2>&1 & echo $! > ${pid_file}
        else
            echo ${application_name} is starting
        fi
}
stop() {
        echo -n $"Shutting down ${application_name} logger: "
        if [[ -f ${pid_file} ]];then
            kill -9 `cat ${pid_file}`
            rm ${pid_file}
        fi
}
rhstatus() {
        status -p "${pid_file}" -l $application_name
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  status)
        rhstatus
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 3
esac

exit $?
